language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- 10.11.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn nps ci
before_deploy:
- cd dist/ngx-dom-wrappers
deploy:
  provider: npm
  skip_cleanup: true
  email: SpaierInstinct@gmail.com
  api_key:
    secure: DG5LOwGzAAr/oRKBgxQmNSqD6m7udEb4Zrmb4YdzZjcB47iCMZ8Ak8dHfHZYulHEmqzKalvgq8XEbMVHzgtNJbPHvH+MTbuPfgqlvhOwZfWBqKRa6emcpyVAYDD4So4VWiVZEPLG98pjNYTI94qI/ZDns56j2V5E44xaCDwmISndN6npiRt8s6YBwrgut1GUpH7/PPnH8AO5ie2b0g7/oMTtUV1ltIa0pvlOLqlXRaOMgybAAzhTPF01PDvND1GsfaXlfulPTwyvFCZ0Bnqg3R8WKiHehVBkzhh024w6omseZhUN9FwsochXjjsrak9zR4qPK/UsCvnHreJa581qtWcjDCI7pcfAV8dq53cZ1nSBt6SU3IC4cZm3WkGSfEnH0FImJFmlEjJME4koMHb2RZiLbnI7qg5LJ38CPtLTrS5KJSthgnjrAhp+7iP6bemVusWqcRA70ZAYYctpxRXdkiOQrwS0rJI6+gBnSCI4ftqJb+fjHqqt0DAf3unhVglVlrDbN5Q9KNt5hZW/D8WbYRQ3AxMbjqaLlyVNzcXGZ51R843euRIDcltX2qFuF75rerRP4OEnJzO7bBofbumyc1nRJ6JeCFLjNFYywbR2vEyKjUdA2pUIZTgM/zjL9ODSdszcu+hIYAjsMtlRMIcWWK6FBb+ObIqQp5KDOKwhq78=
  on:
    tags: true
    branch: master
    repo: Spaier/ngx-dom-wrappers
